[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'leico/autodate.vim'

[[plugins]]
repo = 'cespare/vim-toml'

# [[plugins]]
# repo = 'flrnd/candid.vim'
# hook_add = """
# set background=dark
# colorscheme candid
# """

[[plugins]]
repo = 'ajmwagar/vim-deus'
hook_add = """
set background=dark
colorscheme deus
"""

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = """
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_color_change_percent = 30
let g:indent_guides_guide_size = 1
"""
